image: registry.gitlab.com/wlami/aws-copilot-with-gitlab-2/copilot-cli

stages:
  - env-init
  - env-deploy
  - env-stop
  - svc-deploy

# ----- Preview Env Deployment -----"
.preview-envs:
  resource_group: "$CI_COMMIT_REF_SLUG"
  only:
    refs:
      - branches
    variables:
      - $CI_COMMIT_BRANCH =~ "/feature/"
  environment:
    name: $CI_COMMIT_REF_SLUG
    on_stop: preview-env-stop

preview-env-init:
  extends: .preview-envs
  stage: env-init
  script:
    - sh -x ./scripts/env-init.sh

preview-env-deploy:
  extends: .preview-envs
  stage: env-deploy
  script:
    - sh -x ./scripts/env-deploy.sh

preview-env-stop:
  stage: env-stop
  when: manual
  resource_group: "$CI_COMMIT_REF_SLUG"
  script:
    - sh -x ./scripts/env-stop.sh
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
  variables:
    COPILOT_SERVICE_A: service-a
    COPILOT_SERVICE_B: service-b
  environment:
    name: $CI_COMMIT_REF_SLUG
    action: stop


# ----- Dev Env Deployment -----"
.dev-env:
  resource_group: "dev"
  only:
    refs:
      - branches
    variables:
      - $CI_COMMIT_BRANCH =~ "main"
  environment:
    name: "dev"
    on_stop: dev-env-stop

dev-env-init:
  extends: .dev-env
  stage: env-init
  script:
    - sh -x ./scripts/env-init.sh

dev-env-deploy:
  extends: .dev-env
  stage: env-deploy
  script:
    - sh -x ./scripts/env-deploy.sh


# ----- Service Deployments -----"
.svc-deploy:
  stage: svc-deploy
  before_script:
    - docker info
  script:
    - sh -x ./scripts/svc-deploy.sh

deploy_service-a:
  extends: .svc-deploy
  only:
    changes:
      - service-a/*
      - service-a/app/*
  variables:
    COPILOT_SERVICE: service-a

deploy_service-b:
  extends: .svc-deploy
  only:
    changes:
      - service-b/*
      - service-b/app/*
  variables:
    COPILOT_SERVICE: service-b

# --- Dev Env Stop ---
dev-env-stop:
  extends: .dev-env
  stage: env-stop
  resource_group: "dev"
  when: manual
  script:
    - sh -x ./scripts/env-stop.sh
  variables:
    COPILOT_SERVICE_A: service-a
    COPILOT_SERVICE_B: service-b
  environment:
    name: "dev"
    action: stop

